name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: bring the code.
        run: |
          git clone http://eugene:ghdrldud10@192.168.56.3:3000/eugene/seoyeon-tour.git .


      - name: remove existed container
        run: docker rm -f seoyeon-tour || true

      - name: Docker build
        run: docker build -t seoyeon-tour .

      - name: start container 
        - name: start container
        run: docker run -d --name seoyeon-tour -p 5000:5000 \
          -e TOSS_CLIENT_KEY=test_ck_pP2YxJ4K87Zb1eRbYMkJrRGZwXLO \
          -e TOSS_SECRET_KEY=test_sk_ex6BJGQOVDOvOX22l7v53W4w2zNb \
          -e SESSION_SECRET=ghdrldud10 \
          seoyeon-tour
