name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: bring the code.
        run: |
          git clone http://eugene:ghdrldud10@192.168.56.3:3000/eugene/seoyeon-tour.git .


      - name: remove existed container
        run: docker -rm -f seoyon-project || true

      - name: Docker build
        run: docker build -t seoyon-project

      - name: start container 
        run: docker run -d --name seoyon-project -p 5000:5000 seoyon-project       
